### ISSUE TITLE
Decide on the correct field types to be saved for a Session (for Firestore and Airtable)

### ISSUE THREAD

**Issue by yotamshalev** [haparlament/haparlament-web-app#22]
For firestore:
day - should be saved as enum
feeling - also enum
hourRange - I would save it as 2 fields: hourMin, hourMax which would both be a number from 0 to 23

For Airtable:
@maorcc would like your thoughts on this.

**Comment by yotamshalev** [comment]
current model:
![image](https://user-images.githubusercontent.com/30769427/231083123-4928cdfc-6c26-432e-ada0-e3d9ec4ac99c.png)

**Comment by yotamshalev** [comment]
Let's wait until this [PR](https://github.com/haparlament/haparlament-web-app/pull/15) is merged before starting this.

**Comment by maorcc** [comment]
Airtable can be the same. It has an equivalent to enum called select or multi-select.
