### ISSUE TITLE
Fix UI comments from Amitay

### ISSUE THREAD

**Issue by yotamshalev** [haparlament/haparlament-web-app#26]
intro page:
delete footer and move the CTA a bit down
how does it work subtitle should be closer to the 3 steps
font should be "assistant"
check the color of main CTA button (not according to Figma)

Feelings page:
iphone on edge browser - feelings buttons appear to be blue (missing default color on buttons)
layout doesn't seem right
there is scroll
there should be multi selection for feelings
add some more spacing between feelings and the CTAs
go back to Amitay to decide on the changes to the image selection flow

let's talk page:
 iphone edge - arrow SVG appear with blue background (missing default color on buttons)
progress lines have gray background
add radius 2 to the small rectangle progress lines

time selection page:
change buttons text color to black (missing default color on buttons)
fix confirmation popup text (ask Amitay for the text)
after session request sent successfully, need to redirect to a success page. (ask Amitay for design)

**Comment by AmitayDesign** [comment]
@yotamshalev your capture skills are 💯
If anyone needs a design reference, check out: https://www.figma.com/file/ib5Lu0ctzsmY9IAL4VdVha/Parlament.co?node-id=874%3A13683&t=AVKPxhnCooilC5DA-1

**Comment by SagyBle** [comment]
@AmitayDesign
Just to make sure, the design for the success page is not ready yet, right?

**Comment by yotamshalev** [comment]
@SagyBle - no, I created another ticket for this specific issue:
https://github.com/haparlament/haparlament-web-app/issues/28

**Comment by yotamshalev** [comment]
resolved. These 2 issues will be done separately:
https://github.com/haparlament/haparlament-web-app/issues/27
https://github.com/haparlament/haparlament-web-app/issues/28

@AmitayDesign can you please go over the updated version? (most importantly the iOS issues, which I couldn't reproduce)
